name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: doctave
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: doctave
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: doctave.exe


    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: doctave-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact }}

